#!/usr/bin/env python3
"""
Convert PNG logo to C header in RGB888 format.
Scales logo to fit within flash partition limits.
"""

from PIL import Image
import sys

# Input logo path
LOGO_PATH = "keyboardlogo.png"

# Output header path
OUTPUT_PATH = "main/logo_image.h"

# Target maximum width (will scale proportionally)
MAX_WIDTH = 300

def main():
    print(f"Loading logo from {LOGO_PATH}...")
    logo = Image.open(LOGO_PATH).convert("RGBA")
    original_width, original_height = logo.size

    print(f"Original logo size: {original_width}x{original_height}")

    # Scale down if necessary
    if original_width > MAX_WIDTH:
        scale_factor = MAX_WIDTH / original_width
        new_width = MAX_WIDTH
        new_height = int(original_height * scale_factor)
        print(f"Scaling to {new_width}x{new_height} (scale factor: {scale_factor:.2f})")
        logo = logo.resize((new_width, new_height), Image.Resampling.LANCZOS)
    else:
        new_width = original_width
        new_height = original_height

    # Rotate 90 degrees clockwise for screen orientation
    print("Rotating image 90° clockwise")
    logo = logo.rotate(-90, expand=True)

    logo_width, logo_height = logo.size

    # Flatten transparency onto black background
    black_bg = Image.new("RGB", (logo_width, logo_height), (0, 0, 0))
    black_bg.paste(logo, (0, 0), logo)

    # Convert to RGB888
    print("Converting to RGB888 format...")
    pixels = black_bg.load()
    rgb888_data = []

    for y in range(logo_height):
        for x in range(logo_width):
            r, g, b = pixels[x, y]
            rgb888_data.append(b)  # Blue byte
            rgb888_data.append(g)  # Green byte
            rgb888_data.append(r)  # Red byte

    # Generate C header file
    print(f"Writing C header to {OUTPUT_PATH}...")
    with open(OUTPUT_PATH, 'w') as f:
        f.write("// Auto-generated Tanmatsu logo image\n")
        f.write(f"// Size: {logo_width}x{logo_height}, Format: RGB888 (24-bit)\n")
        f.write("// Generated by convert_logo.py\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define LOGO_WIDTH  {logo_width}\n")
        f.write(f"#define LOGO_HEIGHT {logo_height}\n\n")
        f.write("// RGB888 pixel data (24-bit per pixel, 3 bytes per pixel: R, G, B)\n")
        f.write(f"static const uint8_t logo_image_data[{len(rgb888_data)}] = {{\n")

        # Write data in rows of 12 values for readability
        for i in range(0, len(rgb888_data), 12):
            row = rgb888_data[i:i+12]
            hex_values = ', '.join(f'0x{val:02X}' for val in row)
            f.write(f"    {hex_values},\n")

        f.write("};\n")

    # Calculate size
    num_pixels = len(rgb888_data) // 3
    size_kb = len(rgb888_data) / 1024
    print(f"\nSuccess! Generated {num_pixels} pixels ({size_kb:.1f} KB)")
    print(f"Output: {OUTPUT_PATH}")

if __name__ == "__main__":
    main()
