#!/usr/bin/env perl
use strict;
use warnings;
use Math::Trig;

# Triangle wave generator for musical keyboard
# Generates one complete cycle at base frequency (C4 = 261.63 Hz)
# Output: C header file with waveform data

my $SAMPLE_RATE = 44100;         # Hz
my $BASE_FREQ = 261.63;          # Hz (C4 - middle C)
my $AMPLITUDE = 0.5;             # 50% to prevent clipping with 13 voices

# Calculate samples per cycle
my $samples_per_cycle = int($SAMPLE_RATE / $BASE_FREQ + 0.5);

print STDERR "Generating triangle wave:\n";
print STDERR "  Frequency: $BASE_FREQ Hz (C4)\n";
print STDERR "  Sample rate: $SAMPLE_RATE Hz\n";
print STDERR "  Samples per cycle: $samples_per_cycle\n";
print STDERR "  Amplitude: " . ($AMPLITUDE * 100) . "%\n";

# Generate triangle wave samples
my @samples;
for (my $i = 0; $i < $samples_per_cycle; $i++) {
    my $phase = $i / $samples_per_cycle;  # 0.0 to 1.0
    my $value;

    # Triangle wave: ramp up from -1 to +1, then down from +1 to -1
    if ($phase < 0.5) {
        # Rising edge: -1 to +1
        $value = -1.0 + 4.0 * $phase;
    } else {
        # Falling edge: +1 to -1
        $value = 3.0 - 4.0 * $phase;
    }

    # Scale by amplitude and convert to 16-bit signed integer
    my $sample = int($value * $AMPLITUDE * 32767);
    push @samples, $sample;
}

# Output C header file
print "// Auto-generated triangle waveform for musical keyboard\n";
print "// Base frequency: $BASE_FREQ Hz (C4 - middle C)\n";
print "// Sample rate: $SAMPLE_RATE Hz\n";
print "// Samples per cycle: $samples_per_cycle\n";
print "// Amplitude: " . ($AMPLITUDE * 100) . "%\n";
print "//\n";
print "// Generated by generate_triangle_wave.pl\n";
print "\n";
print "#ifndef KEYBOARD_WAVEFORM_H\n";
print "#define KEYBOARD_WAVEFORM_H\n";
print "\n";
print "#include <stdint.h>\n";
print "\n";
print "// Base frequency for the waveform\n";
print "#define WAVEFORM_BASE_FREQ $BASE_FREQ\n";
print "\n";
print "// Number of samples in one complete waveform cycle\n";
print "#define WAVEFORM_CYCLE_LENGTH $samples_per_cycle\n";
print "\n";
print "// Triangle waveform data (one complete cycle)\n";
print "const int16_t waveform_data[$samples_per_cycle] = {\n";

# Output samples, 10 per line
for (my $i = 0; $i < @samples; $i += 10) {
    print "    ";
    my @chunk = @samples[$i .. min($i + 9, $#samples)];
    print join(", ", @chunk);
    print "," if ($i + 10 < @samples);
    print "\n";
}

print "};\n";
print "\n";
print "#endif // KEYBOARD_WAVEFORM_H\n";

sub min {
    my ($a, $b) = @_;
    return $a < $b ? $a : $b;
}
